#include "cpp_generator.h"

#include <algorithm>
#include <cstring>
#include <sstream>
#include <string>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/descriptor.pb.h>
#include <google/protobuf/io/printer.h>

namespace rpcpio {

using google::protobuf::FileDescriptor;
using google::protobuf::ServiceDescriptor;
using google::protobuf::MethodDescriptor;
using google::protobuf::compiler::GeneratorContext;
using google::protobuf::io::Printer;

// ── Helpers ───────────────────────────────────────────────────────────────────

std::string ProtoBaseName(const std::string& filename) {
    auto dot = filename.rfind('.');
    return dot == std::string::npos ? filename : filename.substr(0, dot);
}

std::string PackageToNamespace(const std::string& package) {
    if (package.empty()) return {};
    std::string ns;
    for (char c : package) {
        ns += (c == '.') ? ':' : c;
        if (c == '.') ns += ':';
    }
    return ns;
}

std::string MethodPath(const MethodDescriptor* m) {
    return "/" + m->service()->full_name() + "/" + m->name();
}

static std::string FullCppType(const google::protobuf::Descriptor* d) {
    // Convert proto full_name to C++ scoped name (handles nested types).
    std::string full = d->full_name();
    // Replace dots with "::" and prepend "::"
    std::string result = "::";
    for (char c : full) {
        result += (c == '.') ? ':' : c;
        if (c == '.') result += ':';
    }
    return result;
}

// ── Header generator ─────────────────────────────────────────────────────────

bool GenerateHeader(const FileDescriptor* file,
                    GeneratedHeader&      out,
                    std::string*          error)
{
    (void)error;  // streaming is now supported; no streaming error path
    std::ostringstream ss;

    ss << "// Generated by rpcpio_cpp_plugin.  DO NOT EDIT.\n";
    ss << "// Source: " << file->name() << "\n\n";
    ss << "#pragma once\n\n";
    ss << "#include \"rpcpio/channel.h\"\n";
    ss << "#include \"rpcpio/server.h\"\n";
    ss << "#include \"rpcpio/status.h\"\n";
    ss << "#include \"rpcpio/unary_method.h\"\n";
    ss << "#include \"rpcpio/streaming_method.h\"\n";
    ss << "#include \"rpcpio/server_reader.h\"\n";
    ss << "#include \"rpcpio/server_writer.h\"\n";
    ss << "#include \"rpcpio/client_reader.h\"\n";
    ss << "#include \"rpcpio/client_writer.h\"\n";
    ss << "#include \"rpcpio/bidi_stream.h\"\n";
    ss << "#include \"" << ProtoBaseName(file->name()) << ".pb.h\"\n\n";

    std::string ns = PackageToNamespace(file->package());
    if (!ns.empty()) {
        ss << "namespace " << ns << " {\n\n";
    }

    for (int si = 0; si < file->service_count(); ++si) {
        const ServiceDescriptor* svc = file->service(si);
        std::string svc_name = svc->name();

        // ── Method descriptors ────────────────────────────────────────────────
        ss << "// Service: " << svc->full_name() << "\n";
        ss << "namespace " << svc_name << "Methods {\n";
        for (int mi = 0; mi < svc->method_count(); ++mi) {
            const MethodDescriptor* m = svc->method(mi);
            bool cs = m->client_streaming();
            bool sv = m->server_streaming();
            std::string req  = FullCppType(m->input_type());
            std::string resp = FullCppType(m->output_type());

            if (!cs && !sv) {
                ss << "inline constexpr ::rpcpio::UnaryMethod<"
                   << req << ", " << resp << ">\n";
                ss << "    " << m->name() << "{\"" << MethodPath(m) << "\"};\n";
            } else if (!cs && sv) {
                ss << "inline constexpr ::rpcpio::ServerStreamingMethod<"
                   << req << ", " << resp << ">\n";
                ss << "    " << m->name() << "{\"" << MethodPath(m) << "\"};\n";
            } else if (cs && !sv) {
                ss << "inline constexpr ::rpcpio::ClientStreamingMethod<"
                   << req << ", " << resp << ">\n";
                ss << "    " << m->name() << "{\"" << MethodPath(m) << "\"};\n";
            } else {
                ss << "inline constexpr ::rpcpio::BidiStreamingMethod<"
                   << req << ", " << resp << ">\n";
                ss << "    " << m->name() << "{\"" << MethodPath(m) << "\"};\n";
            }
        }
        ss << "} // namespace " << svc_name << "Methods\n\n";

        // ── Stub ──────────────────────────────────────────────────────────────
        ss << "class " << svc_name << "Stub {\n";
        ss << "public:\n";
        ss << "    explicit " << svc_name << "Stub(\n";
        ss << "        std::shared_ptr<::rpcpio::Channel> channel)\n";
        ss << "        : channel_(std::move(channel)) {}\n\n";
        for (int mi = 0; mi < svc->method_count(); ++mi) {
            const MethodDescriptor* m = svc->method(mi);
            bool cs = m->client_streaming();
            bool sv = m->server_streaming();
            std::string req  = FullCppType(m->input_type());
            std::string resp = FullCppType(m->output_type());
            if (m->options().deprecated()) {
                ss << "    [[deprecated]]\n";
            }
            if (!cs && !sv) {
                ss << "    ::boost::asio::awaitable<::rpcpio::UnaryResult<" << resp << ">>\n";
                ss << "    " << m->name() << "(\n";
                ss << "        ::rpcpio::ClientContext& ctx,\n";
                ss << "        const " << req << "& request) {\n";
                ss << "        return channel_->UnaryCall(\n";
                ss << "            " << svc_name << "Methods::" << m->name()
                   << ", ctx, request);\n";
                ss << "    }\n\n";
            } else if (!cs && sv) {
                ss << "    ::boost::asio::awaitable<::rpcpio::ClientReader<" << resp << ">>\n";
                ss << "    " << m->name() << "(\n";
                ss << "        ::rpcpio::ClientContext& ctx,\n";
                ss << "        const " << req << "& request) {\n";
                ss << "        return channel_->ServerStreamingCall(\n";
                ss << "            " << svc_name << "Methods::" << m->name()
                   << ", ctx, request);\n";
                ss << "    }\n\n";
            } else if (cs && !sv) {
                ss << "    ::boost::asio::awaitable<::rpcpio::ClientWriter<"
                   << req << ", " << resp << ">>\n";
                ss << "    " << m->name() << "(\n";
                ss << "        ::rpcpio::ClientContext& ctx) {\n";
                ss << "        return channel_->ClientStreamingCall(\n";
                ss << "            " << svc_name << "Methods::" << m->name()
                   << ", ctx);\n";
                ss << "    }\n\n";
            } else {
                ss << "    ::boost::asio::awaitable<::rpcpio::BidiStream<"
                   << req << ", " << resp << ">>\n";
                ss << "    " << m->name() << "(\n";
                ss << "        ::rpcpio::ClientContext& ctx) {\n";
                ss << "        return channel_->BidiStreamingCall(\n";
                ss << "            " << svc_name << "Methods::" << m->name()
                   << ", ctx);\n";
                ss << "    }\n\n";
            }
        }
        ss << "private:\n";
        ss << "    std::shared_ptr<::rpcpio::Channel> channel_;\n";
        ss << "};\n\n";

        // ── Service base ──────────────────────────────────────────────────────
        ss << "class " << svc_name << "Service {\n";
        ss << "public:\n";
        ss << "    virtual ~" << svc_name << "Service() = default;\n\n";
        for (int mi = 0; mi < svc->method_count(); ++mi) {
            const MethodDescriptor* m = svc->method(mi);
            bool cs = m->client_streaming();
            bool sv = m->server_streaming();
            std::string req  = FullCppType(m->input_type());
            std::string resp = FullCppType(m->output_type());
            if (m->options().deprecated()) ss << "    [[deprecated]]\n";
            if (!cs && !sv) {
                ss << "    virtual ::boost::asio::awaitable<::rpcpio::StatusOr<"
                   << resp << ">>\n";
                ss << "    " << m->name() << "(\n";
                ss << "        ::rpcpio::ServerContext& ctx,\n";
                ss << "        const " << req << "& request) = 0;\n\n";
            } else if (!cs && sv) {
                ss << "    virtual ::boost::asio::awaitable<::rpcpio::Status>\n";
                ss << "    " << m->name() << "(\n";
                ss << "        ::rpcpio::ServerContext& ctx,\n";
                ss << "        const " << req << "& request,\n";
                ss << "        ::rpcpio::ServerWriter<" << resp << ">& writer) = 0;\n\n";
            } else if (cs && !sv) {
                ss << "    virtual ::boost::asio::awaitable<::rpcpio::StatusOr<"
                   << resp << ">>\n";
                ss << "    " << m->name() << "(\n";
                ss << "        ::rpcpio::ServerContext& ctx,\n";
                ss << "        ::rpcpio::ServerReader<" << req << ">& reader) = 0;\n\n";
            } else {
                ss << "    virtual ::boost::asio::awaitable<::rpcpio::Status>\n";
                ss << "    " << m->name() << "(\n";
                ss << "        ::rpcpio::ServerContext& ctx,\n";
                ss << "        ::rpcpio::ServerReader<" << req << ">& reader,\n";
                ss << "        ::rpcpio::ServerWriter<" << resp << ">& writer) = 0;\n\n";
            }
        }
        ss << "    void Register(::rpcpio::Server& server);\n";
        ss << "};\n\n";
    }

    if (!ns.empty()) {
        ss << "} // namespace " << ns << "\n";
    }

    out.content = ss.str();
    return true;
}

// ── Source generator ─────────────────────────────────────────────────────────

bool GenerateSource(const FileDescriptor* file,
                    GeneratedSource&      out,
                    std::string*          error)
{
    std::ostringstream ss;

    ss << "// Generated by rpcpio_cpp_plugin.  DO NOT EDIT.\n";
    ss << "// Source: " << file->name() << "\n\n";
    ss << "#include \"" << ProtoBaseName(file->name()) << ".rpcpio.pb.h\"\n\n";

    std::string ns = PackageToNamespace(file->package());
    if (!ns.empty()) {
        ss << "namespace " << ns << " {\n\n";
    }

    for (int si = 0; si < file->service_count(); ++si) {
        const ServiceDescriptor* svc = file->service(si);
        std::string svc_name = svc->name();

        ss << "void " << svc_name << "Service::Register(::rpcpio::Server& server) {\n";
        for (int mi = 0; mi < svc->method_count(); ++mi) {
            const MethodDescriptor* m = svc->method(mi);
            bool cs = m->client_streaming();
            bool sv = m->server_streaming();
            std::string req  = FullCppType(m->input_type());
            std::string resp = FullCppType(m->output_type());

            if (!cs && !sv) {
                ss << "    server.RegisterUnary(\n";
                ss << "        " << svc_name << "Methods::" << m->name() << ",\n";
                ss << "        [this](::rpcpio::ServerContext& ctx,\n";
                ss << "               const " << req << "& req)\n";
                ss << "            -> ::boost::asio::awaitable<::rpcpio::StatusOr<"
                   << resp << ">> {\n";
                ss << "            return this->" << m->name() << "(ctx, req);\n";
                ss << "        });\n";
            } else if (!cs && sv) {
                ss << "    server.RegisterServerStreaming(\n";
                ss << "        " << svc_name << "Methods::" << m->name() << ",\n";
                ss << "        [this](::rpcpio::ServerContext& ctx,\n";
                ss << "               const " << req << "& req,\n";
                ss << "               ::rpcpio::ServerWriter<" << resp << ">& writer)\n";
                ss << "            -> ::boost::asio::awaitable<::rpcpio::Status> {\n";
                ss << "            return this->" << m->name() << "(ctx, req, writer);\n";
                ss << "        });\n";
            } else if (cs && !sv) {
                ss << "    server.RegisterClientStreaming(\n";
                ss << "        " << svc_name << "Methods::" << m->name() << ",\n";
                ss << "        [this](::rpcpio::ServerContext& ctx,\n";
                ss << "               ::rpcpio::ServerReader<" << req << ">& reader)\n";
                ss << "            -> ::boost::asio::awaitable<::rpcpio::StatusOr<"
                   << resp << ">> {\n";
                ss << "            return this->" << m->name() << "(ctx, reader);\n";
                ss << "        });\n";
            } else {
                ss << "    server.RegisterBidi(\n";
                ss << "        " << svc_name << "Methods::" << m->name() << ",\n";
                ss << "        [this](::rpcpio::ServerContext& ctx,\n";
                ss << "               ::rpcpio::ServerReader<" << req << ">& reader,\n";
                ss << "               ::rpcpio::ServerWriter<" << resp << ">& writer)\n";
                ss << "            -> ::boost::asio::awaitable<::rpcpio::Status> {\n";
                ss << "            return this->" << m->name() << "(ctx, reader, writer);\n";
                ss << "        });\n";
            }
        }
        ss << "}\n\n";
    }

    if (!ns.empty()) {
        ss << "} // namespace " << ns << "\n";
    }

    out.content = ss.str();
    return true;
}

// ── CppGenerator::Generate ────────────────────────────────────────────────────

bool CppGenerator::Generate(const FileDescriptor* file,
                             const std::string&    /*parameter*/,
                             GeneratorContext*      context,
                             std::string*           error) const
{
    if (file->service_count() == 0) return true;  // nothing to generate

    std::string base = ProtoBaseName(file->name());

    auto write_to_stream = [&](const std::string& content,
                                const std::string& filename) -> bool {
        std::unique_ptr<google::protobuf::io::ZeroCopyOutputStream> stream(
            context->Open(filename));
        const char* src       = content.data();
        std::size_t remaining = content.size();
        while (remaining > 0) {
            void* buf;
            int   buf_size;
            if (!stream->Next(&buf, &buf_size)) return false;
            auto n = std::min<std::size_t>(remaining, static_cast<std::size_t>(buf_size));
            std::memcpy(buf, src, n);
            if (static_cast<std::size_t>(buf_size) > n)
                stream->BackUp(static_cast<int>(buf_size) - static_cast<int>(n));
            src       += n;
            remaining -= n;
        }
        return true;
    };

    // Header
    {
        GeneratedHeader hdr;
        if (!GenerateHeader(file, hdr, error)) return false;
        if (!write_to_stream(hdr.content, base + ".rpcpio.pb.h")) return false;
    }

    // Source
    {
        GeneratedSource src_out;
        if (!GenerateSource(file, src_out, error)) return false;
        if (!write_to_stream(src_out.content, base + ".rpcpio.pb.cc")) return false;
    }

    return true;
}

uint64_t CppGenerator::GetSupportedFeatures() const {
    return FEATURE_PROTO3_OPTIONAL;
}

} // namespace rpcpio
