package(default_visibility = [
    "//tests:__subpackages__",
    "//examples:__subpackages__",
    "//src:__pkg__",
])

cc_library(
    name = "client",
    srcs = [
        "call_state.cc",
        "channel_impl.cc",
    ],
    hdrs = [
        "call_state.h",
        "channel_impl.h",
    ],
    copts = ["-std=c++20"],
    deps = [
        "//include:rpcpio_hdrs",
        "//src/protocol:protocol",
        "@nghttp2-asio//:nghttp2_asio",
    ],
)
